### ISSUE TITLE
[BUG] Setting a custom module's value using a chat command doesn't work

### ISSUE THREAD

**Issue by Teoremi** [CCBlueX/LiquidBounce1.8-Issues#3764] opened 2020-06-07 15:37 UTC
**Describe the bug**

In the latest update, setting a custom script value with a chat command doesn't work. 

**To Reproduce**

1. Install any custom script (Legacy or v2 script doesn't matter)
2. Try to set any custom script value with a chat
command

**Additional information:**
 - OS: Windows 10
 - LiquidBounce B72
 - Minecraft Version 1.8.9

**Comment by SenkJu** [comment] 2020-06-08 22:11
I can't reproduce the problem. It's working for me. Could you send me a script that isn't working properly for you? I will close this for now.

**Closed by SenkJu** 2020-06-08 22:11 UTC
Labels: Client Bug, JavaScript API

**Comment by Teoremi** [comment] 2020-06-09 04:19
Every legacy and new script that I tested isn't able to be chat configured, even the example bhop from the official scriptapi repo isn't able to

**Comment by Teoremi** [comment] 2020-06-09 05:51
![23](https://user-images.githubusercontent.com/66556966/84110774-5909ca80-a9da-11ea-81a5-e7df52307700.PNG)
![24](https://user-images.githubusercontent.com/66556966/84110779-5c04bb00-a9da-11ea-8471-e215d7f24e34.PNG)

Here are some screenshots regarding the issue
