### ISSUE TITLE
[BUG] Reloading scripts kicks since b63

### ISSUE THREAD

**Issue by mrphax0r** [CCBlueX/LiquidBounce1.8-Issues#3037] opened 2019-07-16 18:10 UTC
Steps to reproduce(unstable) :
1. Make a script
2. Enable the module
(DO NOT TOGGLE IT OFF AS MODULEMANAGER IS SUPPOSED TO DO THIS)
3. Change the script
4. See you get kicked from whatever server you're on.
There might be multiple attempts needed.
***Very*** annoying. 
Note that this bug die not exist in b62.

**Comment by yKsenomorf** [comment] 2019-07-16 18:24
Any logs/screenshots applicable?

**Comment by mrphax0r** [comment] 2019-07-16 18:27
Not at the moment because i am not at home, but the kick message was Java.util. ...

**Comment by CzechHek** [comment] 2019-07-17 18:52
If you are in singleplayer it crashes the game.

**Comment by mrphax0r** [comment] 2019-07-21 10:36
Oof

**Comment by mrphax0r** [comment] 2019-07-21 10:36
Definitely needs fixing

**Comment by Marco09MC** [comment] 2019-07-29 03:23
Logs?

**Comment by SenkJu** [comment] 2019-08-07 15:06
Are you sure this is not a problem with your script?

**Comment by SenkJu** [comment] 2019-08-08 16:28
I am closing this for now as I cannot reproduce this problem.

**Closed by SenkJu** 2019-08-08 16:28 UTC
Labels: Client Bug, JavaScript API, Unverified

**Comment by DeleteAndInsert** [comment] 2019-08-08 20:44
@SenkJu wait, wait. Thats problem is for me too, using my old srcipts.

**Comment by Shiv3RPolak** [comment] 2019-08-09 06:57
oof this problem is annoying. Imo .reload should first reload scripts (.scripts reload) and after that reload other stuff and this will stop crashing game if something in script is broken.

**Comment by SenkJu** [comment] 2019-08-09 11:41
We need a crash log @DeleteAndInsert

**Comment by mrphax0r** [comment] 2019-08-16 17:11
java.util.concurrentModificationException.
@SenkJu

**Comment by mrphax0r** [comment] 2019-08-16 17:13
Maybe you could review the changes you made to the API since b62?

**Comment by mrphax0r** [comment] 2019-08-16 17:14
Maybe you could review the changes you made to the API since b62?

**Comment by SenkJu** [comment] 2019-08-17 13:41
I need a full crash log

**Comment by CzechHek** [comment] 2020-03-09 19:30
https://github.com/CCBlueX/LiquidBounce/pull/68
https://github.com/CCBlueX/LiquidBounce/pull/69
