### ISSUE TITLE
[FEATURE] ProxyManager

### ISSUE THREAD

**Issue by Timeox2k** [CCBlueX/LiquidBounce1.8-Issues#3841] opened 2020-06-23 22:08 UTC
**Describe your feature request.**
The possibility to use Proxys, like clipboard Proxy so you can press the Button then it uses theProxy like in Wurst .proxy command.

**Comment by Teals53** [comment] 2020-06-23 22:10
duplicated ?

**Comment by Timeox2k** [comment] 2020-06-23 22:35
no, one is Tor one is ProxyManager

**Comment by SenkJu** [comment] 2020-06-23 22:43
Duplicate of #2009

**Closed by SenkJu** 2020-06-23 22:43 UTC
