### ISSUE TITLE
[Feature] Blockcap

### ISSUE THREAD

**Issue by DGWAsureX** [CCBlueX/LiquidBounce1.8-Issues#3650] opened 2020-04-20 11:25 UTC
I would recomend a inventoryCleaner blockcap mode to configure the maximum capacity of blocks in your inventory.

**Comment by WentilatorWentox** [comment] 2020-04-20 16:18
as far as I know, this is already planned in the recode

**Comment by DGWAsureX** [comment] 2020-04-20 18:15
> as far as I know, this is already planned in the recode of the invcleaner

When will it come out about

**Comment by WentilatorWentox** [comment] 2020-04-20 19:48
idk but heres the issue
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3604

**Comment by NurMarvin** [comment] 2020-04-24 13:17
Duplicate of #3604

**Closed by NurMarvin** 2020-04-24 13:17 UTC
Labels: Invalid
