### ISSUE TITLE
Diagonal Expand scaffold not working sometimes

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#2862] opened 2019-02-15 12:52 UTC
https://streamable.com/zsfo7
Same goes for jump sprint scaffold
This is a problem since Normal scaffold is detected on Plex

**Comment by CzechHek** [comment] 2020-06-17 17:59
Probably fixed, close this.

**Comment by superblaubeere27** [comment] 2020-06-17 18:50
No @CzechHek

**Closed** 2020-06-17 18:51 UTC
Labels: Works as intended

**Comment by Teals53** [comment] 2020-06-17 18:55
if no why u closed that ? @superblaubeere27

**Comment by superblaubeere27** [comment] 2020-06-17 19:16
Because it `Works as intended`?

**Comment by Teals53** [comment] 2020-06-17 23:07
true im stupit blind

**Comment by yorik100** [comment] 2020-06-17 23:46
The fuck what, I'm at the border of a block and pressing forward, my player isn't moving and 0 blocks are getting placed
