### ISSUE TITLE
[BYPASS] AAC 4.0.11 "Aimbot"/Killaura

### ISSUE THREAD

**Issue by Mspy1** [CCBlueX/LiquidBounce1.8-Issues#3054] opened 2019-07-26 13:39 UTC
AAC Flags both Killaura, Scaffold and Aimbot whilst jumping, you can see me getting flagged because of the aimbot in the video. 
https://www.youtube.com/watch?v=xf0cBR4Vb1o

**Comment by Mspy1** [comment] 2019-07-26 14:45
I've tested several other clients' aimbots, Impact's random SmoothAim bypasses.

**Comment by CzechHek** [comment] 2019-07-26 19:23
It's mostly movement flags that can be fixed with config, but the killaura flags are caused by bug in killaura that makes it aim too up when jumping.

**Comment by je5442804** [comment] 2019-07-27 00:25
Impact Client have mc 1.8 verison?

**Comment by Mspy1** [comment] 2019-07-27 06:49
idk, does it matter?

**Comment by Mspy1** [comment] 2019-07-27 12:54
Killaura clip: https://youtu.be/7Z3EUP30FY8

**Comment by scorpion3013** [comment] 2019-07-27 15:46
Most of the flags from the killaura are there because the player can only walk in 8 ways. ![legit](https://axolotl.church/N5a9UoDE.png?key=qj7fifOaEbOjkQ)

With killaura on you walk in a direction which is not possible based on the serverside rotation
![unlegit](https://axolotl.lol/Qh2ACCAR.png?key=1rrFbnGHfkr9pR)

**Comment by Mspy1** [comment] 2019-07-27 16:27
So it will be hard to implement a solution on this problem.

**Comment by Marco09MC** [comment] 2019-07-29 03:16
> 
> 
> It's mostly movement flags that can be fixed with config, but the killaura flags are caused by bug in killaura that makes it aim too high when jumping.

That's not a bug. The killaura try to find the nearest point to the crosshair (server-side).

**Comment by Soulplexis** [comment] 2019-08-04 00:28
> 
> 
> Most of the flags from the killaura are there because the player can only walk in 8 ways. ![legit](https://camo.githubusercontent.com/15cbb14bd1f6e67d668c0382b555d5f0e96c01b4/68747470733a2f2f61786f6c6f746c2e6368757263682f4e356139556f44452e706e673f6b65793d716a376669664f6145624f6a6b51)
> 
> With killaura on you walk in a direction which is not possible based on the serverside rotation
> ![unlegit](https://camo.githubusercontent.com/ed7b30de62d12910c8a0a4598ed0d6f0cfdd112e/68747470733a2f2f61786f6c6f746c2e6c6f6c2f51683241434341522e706e673f6b65793d31727246626e4748666b72397052)

that second picture isnt it backwards?! serverside rotation wuld be where killaura is telling the server you aim?

**Comment by scorpion3013** [comment] 2019-08-04 15:29
> that second picture isnt it backwards?! serverside rotation wuld be where killaura is telling the server you aim?

The serverside rotation is the killaura rotation?

**Comment by Soulplexis** [comment] 2019-08-04 17:42
> 
> 
> > that second picture isnt it backwards?! serverside rotation wuld be where killaura is telling the server you aim?
> 
> The serverside rotation is the killaura rotation?
> The image is correct as it is

i would think that serverside meant what rotations the server believes and clientside is where the client is at and anyway 

i tested on poke and killaura doesnt seem to flag there even going at the impossible direction
but if it did a bypass might look something like using left, right, left , right etc. to simulate tapping wdwdwdwdwdwdwd really fast, you can move at those impossible angles if you switch what key is pressed very fast.

**Comment by Mspy1** [comment] 2019-08-11 13:09
Meanwhile, aimbot is fully detected right now after new AAC update, you don't even have to jump for it to flag you.

**Closed** 2020-01-02 09:28 UTC
Labels: Bypass, Module, Request, Setting
