### ISSUE TITLE
[FEATURE] onChangeSetting SkriptAPI

### ISSUE THREAD

**Issue by max4k0** [CCBlueX/LiquidBounce1.8-Issues#3952] opened 2020-09-20 08:47 UTC
**Describe your feature request.**
If I create a module xy and change settings there, I want to call this event on every settings change. 
Even if the module is switched off this event should be executed.

This event would have many advantages. First of all you don't always have to check in onUpdate if a module has changed if only a single code is executed.

And secondly you can execute code even if the module is off.

For example if there are 3 settings, but only a maximum of 2 may be on, then it is possible to check this with this event. 

Or if settings should only be displayed if you have activated the appropriate mode. Then this would not work if the module is switched off. With this event it would work.
Optional:
You can still use eventdatas, for example which setting you have changed. 

If I create a module xy and change settings there, I want to call this event on every settings change. 
Even if the module is switched off this event should be executed.

This event would have many advantages. First of all you don't always have to check in onUpdate if a module has changed if only a single code is executed.

And secondly you can execute code even if the module is off.

For example if there are 3 settings, but only a maximum of 2 may be on, then it is possible to check this with this event. 

Or if settings should only be displayed if you have activated the appropriate mode. Then this would not work if the module is switched off. With this event it would work.
Optional:
You can still use eventdatas, for example which setting you have changed.

**Comment by CzechHek** [comment] 2020-09-20 10:06
Already doable, example:
https://github.com/CzechHek/Core/blob/master/Scripts/InventoryManager.js

**Comment by max4k0** [comment] 2020-09-20 16:06
No.

**Comment by max4k0** [comment] 2020-09-20 16:09
onChangeSetting does not exist yet. I am aware that you can hide the settings. But it causes problems if I want the settings to be hidden or shown when the module is off. If I add an interval timer for each of my modules, the FPS will go into the basement. onChangeSetting is not supposed to offer new features, but onChangeSetting is supposed to increase the performance. Otherwise I can simply start an interval timer, obfuscate my script and everybody has problems even with more powerful devices Fps.

And I can even correct myself. There is no event that is called when the module is switched off. onChangeSetting would be the first. And apart from the performance-guzzling interval timer there is nothing. You would also have to set the interval timer quite small, so that the gui runs correctly, which reduces the performance even more.

**Comment by SenkJu** [comment] 2020-09-20 16:10
Duplicate of https://github.com/CCBlueX/LiquidBounce-Issues/issues/3793

**Closed as completed by SenkJu** 2020-09-20 16:11 UTC
