### ISSUE TITLE
[FEATURE]improve arraylist 

### ISSUE THREAD

**Issue by idkwhoisme** [CCBlueX/LiquidBounce1.8-Issues#3849] opened 2020-06-28 11:12 UTC
pls make full rect arraylist like this 
![image](https://user-images.githubusercontent.com/67542963/85945890-e5206980-b96a-11ea-9bc1-debf519d2bf2.png)

**Comment by Teals53** [comment] 2020-06-28 17:05
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/1959#issuecomment-650304437

**Comment by Teals53** [comment] 2020-06-28 17:06
also can u tell me where u find this scripts for rect for targetstrafe and other ones ?

**Comment by superblaubeere27** [comment] 2020-06-28 23:35
Duplicate of #1959

**Closed by superblaubeere27** 2020-06-28 23:35 UTC
