### ISSUE TITLE
[FEATURE] CustomHUD with Draw Rect and Lined ArrayList

### ISSUE THREAD

**Issue by 1337quip** [CCBlueX/LiquidBounce1.8-Issues#3792] opened 2020-06-12 16:44 UTC
**Describe your feature request.**
I think if LiquidBounce in the future has a CustomHUD that can draw Rect and ArrayList with Lined, it will make LiquidBounce HUD more beautiful.

Picture: https://i.imgur.com/iaFnw4e.png

**Additional context**
I think your CustomHUD is better

**Comment by SenkJu** [comment] 2020-06-12 16:46
Duplicate of #1959

**Closed** 2020-06-12 16:46 UTC
