### ISSUE TITLE
Bypass Reflex Killaura

### ISSUE THREAD

**Issue by cui0v0** [CCBlueX/LiquidBounce1.8-Issues#997] opened 2017-07-08 01:08 UTC
Reflex is a AntiCheat can block LiquidBounce's Killaura Bypass.
When I opened the AAC and RayCast options , but it also can kick me.It was so bad. :(
AntiBots can bypass Reflex's bots but Killaura can't bypass.
I hope you can add the Reflex Killaura. Thanks :)
And my English is not very good , please understand :)

**Comment by MaxHD0** [comment] 2017-07-08 10:24
"And my English is not very good , please understand :)"

dann kannst du auch deutsch sprechen^^ (falls das deine hauptsprache ist)

Wasinvis bei Antibot ist für reflex. Das problem ist das AAC Wasinvis wertlos macht. Und wenn ein server AAC und reflex hat funktioniert Wasinvis nicht :-( ich schätze es wird behoben.

**Comment by MaxHD0** [comment] 2017-07-08 10:24
das wurde bereits angesprochen. #988

**Comment by cui0v0** [comment] 2017-07-08 10:45
Sorry , In fact , I am a Chinese . So, I only can speak Chinese and English (But not good) . I can't speak German :(

**Comment by MaxHD0** [comment] 2017-07-08 20:52
Oh. Wasinvis at Antibot is for reflex. The problem is the AAC Wasinvis makes worthless. And if a server AAC and reflex has worked Wasinvis not :-( I guess it will be fixed.

**Comment by Marco-MC** [comment] 2017-07-30 23:02
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/297

**Closed by Marco-MC** 2017-07-30 23:02 UTC
Labels: Bypass, Feature request
