### ISSUE TITLE
FastUse Timer mode

### ISSUE THREAD

**Issue by ghost** [CCBlueX/LiquidBounce1.8-Issues#2471] opened 2018-08-16 07:18 UTC
Working on hypixel

**Comment by liamjdorsey** [comment] 2018-10-19 21:55
why? it makes it basically no faster and if the item will not finish and you use it too long, you get autoban

**Comment by ClientvsAnticheat** [comment] 2018-10-29 21:29
Useless and Duplicate of #2686

**Closed** 2018-10-31 02:39 UTC
Labels: Module, Request, Setting

**Comment by 215789586** [comment] 2019-01-29 08:02
in fact fastuse aac mode bypasses hypixel(a lot of chinese configuration-maker use it ans bypasses hypixel)

**Comment by 215789586** [comment] 2019-01-29 08:03
i think fastuse aac mode is just timer
