### ISSUE TITLE
[BUG] Killaura Keepsprint

### ISSUE THREAD

**Issue by yorik100** [CCBlueX/LiquidBounce1.8-Issues#3590] opened 2020-02-23 00:09 UTC
**Describe the bug**
Disabling it makes you slow down way more than a normal person should while hitting, that's how AGC detects LB's aura

**To Reproduce**

**Screenshots**

**Additional information:**
 - LiquidBounce Build Version [e.g. b61]
 - Minecraft Version [e.g. 1.8.9]

**Comment by NurMarvin** [comment] 2020-04-09 17:56
Closing since we weren't able to reproduce this bug.

**Closed by NurMarvin** 2020-04-09 17:56 UTC
Labels: Invalid
