### ISSUE TITLE
[BUG] ChestStealer only takes items with highest dmg

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3469] opened 2020-01-28 18:05 UTC
**Describe the bug**
#3462 
ChestStealer won't take any tool with lower dmg than you have.

[Video](https://ctrlv.tv/video/2020/01/28/18/npWO.webm)

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version Latest b70
 - Minecraft Version 1.8.9

**Comment by CzechHek** [comment] 2020-01-28 18:10
oh and there is also some [color issue](https://ctrlv.tv/video/2020/01/28/18/KOz1.webm), appears in all b70 that I played with

**Comment by Lytexx** [comment] 2020-01-28 20:40
yeah i get the same issue that the hand gets blue sometimes

**Comment by superblaubeere27** [comment] 2020-01-28 21:31
What is the problem with this? And please create a second issue for the second bug

**Comment by CzechHek** [comment] 2020-01-28 21:34
It's the same problem as #3462 but with ChestStealer ignoring now.

**Comment by superblaubeere27** [comment] 2020-01-28 21:38
Yes. This isn't a bug. It is a feature of ChestStealer and InvCleaner. It prevents flooding your inventory with douzens of tools of the same type.

**Comment by CzechHek** [comment] 2020-01-28 21:40
You don't get any tools if you take sword first since sword has the highest dmg?

**Comment by Toxikk9** [comment] 2020-01-28 21:45
smrdis

**Comment by yorik100** [comment] 2020-01-28 21:47
> 
> 
> Yes. This isn't a bug. It is a feature of ChestStealer and InvCleaner. It prevents flooding your inventory with douzens of tools of the same type.

That's not the idea, even if you don't have a pick, it'll not take a pick out of a chest, same for the axe

**Comment by superblaubeere27** [comment] 2020-01-28 21:53
> 
> 
> > Yes. This isn't a bug. It is a feature of ChestStealer and InvCleaner. It prevents flooding your inventory with douzens of tools of the same type.
> 
> That's not the idea, even if you don't have a pick, it'll not take a pick out of a chest, same for the axe

Yes it is. For example, if your hotbar shouldn't have an axe in it, an axe is assumed as useless and it's going to be thrown away or not even picked up at all. What you describe isn't a bug, it is the way it is intended to be. If you want to have an option to change that, please create a feature request.

**Comment by yorik100** [comment] 2020-01-28 22:39
> 
> 
> > > Yes. This isn't a bug. It is a feature of ChestStealer and InvCleaner. It prevents flooding your inventory with douzens of tools of the same type.
> > 
> > 
> > That's not the idea, even if you don't have a pick, it'll not take a pick out of a chest, same for the axe
> 
> Yes it is. For example, if your hotbar shouldn't have an axe in it, an axe is assumed as useless and it's going to be thrown away or not even picked up at all. What you describe isn't a bug, it is the way it is intended to be. If you want to have an option to change that, please create a feature request.

1. Get an empty inventory
2. Put an axe and a pick in a chest
3. Enable cheststealer
4. ChestStealer no steal :O

**Comment by superblaubeere27** [comment] 2020-01-28 22:41
@yorik100 This bug is in b69 and it was fixed with #3462

**Comment by CzechHek** [comment] 2020-01-28 22:43
This bug isn't in b69 and in #3462 was fixed InvCleaner.

However ChestStealer has the same bug shown in this video after #3462, shown in [this video](https://ctrlv.tv/video/2020/01/28/18/npWO.webm).

Exactly the same problem caused by #2788

**Comment by superblaubeere27** [comment] 2020-01-28 22:48
I was able to reproduce it.

**Closed** 2020-01-29 13:12 UTC
Labels: Client Bug
