### ISSUE TITLE
[BUG] ChestStealer taking useless stuff

### ISSUE THREAD

**Issue by CzechHek** [CCBlueX/LiquidBounce1.8-Issues#3602] opened 2020-02-25 18:29 UTC
**Describe the bug**
ChestStealer doesn't ignore worse tools when InventoryCleaner is on.
It will take exactly 2 tools and then close the chest.

**Video**
[https://youtu.be/sfmhrXRJ5d0](https://youtu.be/sfmhrXRJ5d0)

**Additional information:**
 - OS: Win 10 64bit
 - LiquidBounce Build Version b71
 - Minecraft Version 1.8.9

**Comment by superblaubeere27** [comment] 2020-02-26 19:13
Not a bug, rather an improvement. I think this would be one of the first things to address in a recode of InvCleaner. I made an issue for this purpose. #3604

**Comment by superblaubeere27** [comment] 2020-02-26 19:16
Since a rework would cover this (well-known) problem I will close this one even tho it is a legitimate issue ;D

**Closed by superblaubeere27** 2020-02-26 19:16 UTC
Labels: Improve
